# Generated by Django 5.0.7 on 2024-11-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='level',
        ),
    ]
