# Generated by Django 5.0.7 on 2024-12-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_customer_department_remove_customer_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='n'),
            preserve_default=False,
        ),
    ]
